const types = {
	USUARIO_AUTENTICADO: 'USUARIO_AUTENTICADO',
	USUARIO_AUTENTICADO_ERROR : 'USUARIO_AUTENTICADO_ERROR',
	REGISTRO_EXITOSO: 'REGISTRO_EXITOSO',
	LOGIN_ERROR: 'LOGIN_ERROR',
	CERRAR_SESION: 'CERRAR_SESION',
	SUBIR_ARCHIVO: 'SUBIR_ARCHIVO',
	SUBIR_ARCHIVO_SUCCESS: 'SUBIR_ARCHIVO_SUCCESS',
	SUBIR_ARCHIVO_ERROR: 'SUBIR_ARCHIVO_ERROR',
	CREAR_ENLACE_SUCCESS: 'CREAR_ENLACE_SUCCESS',
	CREAR_ENLACE_ERROR: 'CREAR_ENLACE_ERROR',
	MOSTRAR_ERROR: 'MOSTRAR_ERROR',
	BORRAR_ERROR: 'BORRAR_ERROR',
	RESET_STATE: 'RESET_STATE'
}

export default types
